/*
 * This file was automatically generated by EvoSuite
 * Fri Aug 28 13:47:36 GMT 2026
 */

package org.apache.avro;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.fasterxml.jackson.core.JsonFactory;
import com.fasterxml.jackson.core.JsonGenerator;
import com.fasterxml.jackson.core.JsonParser;
import com.fasterxml.jackson.core.filter.FilteringParserDelegate;
import com.fasterxml.jackson.core.filter.TokenFilter;
import com.fasterxml.jackson.core.io.ContentReference;
import com.fasterxml.jackson.core.io.IOContext;
import com.fasterxml.jackson.core.json.ReaderBasedJsonParser;
import com.fasterxml.jackson.core.sym.CharsToNameCanonicalizer;
import com.fasterxml.jackson.core.util.BufferRecycler;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.cfg.DeserializerFactoryConfig;
import com.fasterxml.jackson.databind.deser.BeanDeserializerFactory;
import com.fasterxml.jackson.databind.deser.DefaultDeserializationContext;
import com.fasterxml.jackson.databind.node.ArrayNode;
import com.fasterxml.jackson.databind.node.BooleanNode;
import com.fasterxml.jackson.databind.node.FloatNode;
import com.fasterxml.jackson.databind.node.JsonNodeFactory;
import com.fasterxml.jackson.databind.node.NumericNode;
import com.fasterxml.jackson.databind.node.ObjectNode;
import com.fasterxml.jackson.databind.node.TextNode;
import com.fasterxml.jackson.databind.ser.DefaultSerializerProvider;
import com.fasterxml.jackson.databind.util.TokenBuffer;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.InputStream;
import java.io.PushbackInputStream;
import java.io.StringReader;
import java.net.URI;
import java.nio.file.FileVisitResult;
import java.util.Collection;
import java.util.HashMap;
import java.util.LinkedHashSet;
import java.util.LinkedList;
import java.util.List;
import java.util.PriorityQueue;
import java.util.Set;
import java.util.Stack;
import java.util.TreeSet;
import java.util.Vector;
import org.apache.avro.LogicalType;
import org.apache.avro.NameValidator;
import org.apache.avro.ParseContext;
import org.apache.avro.Protocol;
import org.apache.avro.Schema;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.mock.java.io.MockFile;
import org.evosuite.runtime.mock.java.net.MockURI;
import org.evosuite.runtime.testdata.FileSystemHandling;
import org.junit.runner.RunWith;

public class SchemaESTest {

  @Test(timeout = 4000)
  public void test000() throws Throwable {
    FileSystemHandling fileSystemHandling0 = new FileSystemHandling();
    Schema.Name schema_Name0 = new Schema.Name("default", "default");
    schema_Name0.getQualified("Not a map: ");
    // Undeclared exception!
    try {
      Schema.parse("default.default", true);
      fail("Expecting exception: RuntimeException");

    } catch (RuntimeException e) {
      //
      // com.fasterxml.jackson.core.JsonParseException: Unrecognized token 'default':
      // was expecting (JSON String, Number, Array, Object or token 'null', 'true' or
      // 'false')
      // at [Source: (String)\"default.default\"; line: 1, column: 8]
      //
      verifyException("org.apache.avro.Schema$Parser", e);
    }
  }

  @Test(timeout = 4000)
  public void test001() throws Throwable {
    Schema.Parser schema_Parser0 = new Schema.Parser();
    // Undeclared exception!
    try {
      schema_Parser0.parseInternal(") not VALUE_STRING or VALUE_EMBEDDED_OBJECT, can not access as binary");
      fail("Expecting exception: RuntimeException");

    } catch (RuntimeException e) {
      //
      // com.fasterxml.jackson.core.JsonParseException: Unexpected character (')'
      // (code 41)): expected a valid value (JSON String, Number, Array, Object or
      // token 'null', 'true' or 'false')
      // at [Source: (String)\") not VALUE_STRING or VALUE_EMBEDDED_OBJECT, can not
      // access as binary\"; line: 1, column: 2]
      //
      verifyException("org.apache.avro.Schema$Parser", e);
    }
  }

  @Test(timeout = 4000)
  public void test002() throws Throwable {
    Schema.Names schema_Names0 = new Schema.Names("!a8xGd.7c!,x+:)##?");
    // Undeclared exception!
    try {
      schema_Names0.get(".$UU6y*nLy}`]9");
      fail("Expecting exception: RuntimeException");

    } catch (RuntimeException e) {
      //
      // Illegal initial character: $UU6y*nLy}`]9
      //
      verifyException("org.apache.avro.Schema", e);
    }
  }

  @Test(timeout = 4000)
  public void test003() throws Throwable {
    Stack<Schema.Field> stack0 = new Stack<Schema.Field>();
    Schema schema0 = Schema.createRecord("q=42B(=W!Q;$4tt.namespace", (String) null,
        "com.fasterxml.jackson.databind.ser.std.ClassSerializer", true, (List<Schema.Field>) stack0);
    assertNull(schema0.getDoc());
  }

  @Test(timeout = 4000)
  public void test004() throws Throwable {
    NameValidator nameValidator0 = Schema.getNameValidator();
    ParseContext parseContext0 = new ParseContext(nameValidator0);
    Schema schema0 = parseContext0.find("org.apache.avro.compiler.UnresolvedSchema_14",
        "org.apah.avro.c'mpiler.UnresolvedSHhema_1");
    schema0.addProp("boolean", "");
    assertEquals("unresolved schema", schema0.getDoc());
  }

  @Test(timeout = 4000)
  public void test005() throws Throwable {
    NameValidator nameValidator0 = Schema.getNameValidator();
    Schema.setNameValidator(nameValidator0);
  }

  @Test(timeout = 4000)
  public void test006() throws Throwable {
    Schema schema0 = Protocol.SYSTEM_ERROR;
    Schema.Field schema_Field0 = new Schema.Field("default", schema0, "-8", (Object) null);
    assertEquals("-8", schema_Field0.doc());
    assertEquals((-1), schema_Field0.pos());
  }

  @Test(timeout = 4000)
  public void test007() throws Throwable {
    Schema schema0 = Protocol.SYSTEM_ERRORS;
    TextNode textNode0 = new TextNode((String) null);
    boolean boolean0 = schema0.isValidDefault(textNode0);
    assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test008() throws Throwable {
    Schema schema0 = Protocol.SYSTEM_ERRORS;
    boolean boolean0 = schema0.isUnion();
    assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test009() throws Throwable {
    Schema schema0 = Schema.createRecord((String) null, (String) null, "Order cannot be null", true);
    boolean boolean0 = schema0.isError();
    assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test010() throws Throwable {
    Stack<Schema.Field> stack0 = new Stack<Schema.Field>();
    Schema schema0 = Schema.createRecord((List<Schema.Field>) stack0);
    boolean boolean0 = schema0.isError();
    assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test011() throws Throwable {
    LinkedList<Schema> linkedList0 = new LinkedList<Schema>();
    Schema schema0 = Schema.createUnion((List<Schema>) linkedList0);
    List<Schema> list0 = schema0.getTypes();
    assertFalse(list0.contains(schema0));
  }

  @Test(timeout = 4000)
  public void test012() throws Throwable {
    Schema schema0 = Protocol.SYSTEM_ERRORS;
    List<Schema> list0 = schema0.getTypes();
    assertFalse(list0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test013() throws Throwable {
    Schema schema0 = Protocol.SYSTEM_ERRORS;
    Schema.Type schema_Type0 = schema0.getType();
    assertEquals("union", schema_Type0.getName());
  }

  @Test(timeout = 4000)
  public void test014() throws Throwable {
    Schema.LockableArrayList<String> schema_LockableArrayList0 = new Schema.LockableArrayList<String>();
    Schema schema0 = Schema.createEnum((String) null, "o", "&lW{b!95*0x[", (List<String>) schema_LockableArrayList0);
    schema0.getNamespace();
    assertEquals("o", schema0.getDoc());
  }

  @Test(timeout = 4000)
  public void test015() throws Throwable {
    Schema schema0 = Schema.createRecord((String) null, (String) null, (String) null, false);
    String string0 = schema0.getFullName();
    assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test016() throws Throwable {
    Stack<Schema.Field> stack0 = new Stack<Schema.Field>();
    Schema schema0 = Schema.createRecord((List<Schema.Field>) stack0);
    List<Schema.Field> list0 = schema0.getFields();
    assertTrue(list0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test017() throws Throwable {
    Schema.LockableArrayList<String> schema_LockableArrayList0 = new Schema.LockableArrayList<String>();
    Schema schema0 = Schema.createEnum("pr6fixes", "pr6fixes", (String) null, (List<String>) schema_LockableArrayList0);
    String string0 = schema0.getEnumDefault();
    assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test018() throws Throwable {
    Schema.LockableArrayList<String> schema_LockableArrayList0 = new Schema.LockableArrayList<String>();
    Schema schema0 = Schema.createEnum("prefixes", "prefixes", "prefixes", (List<String>) schema_LockableArrayList0);
    String string0 = schema0.getDoc();
    assertEquals("prefixes", string0);
  }

  @Test(timeout = 4000)
  public void test019() throws Throwable {
    Schema schema0 = Schema.createRecord((String) null, (String) null, "Order cannot be null", true);
    Set<String> set0 = schema0.getAliases();
    assertFalse(set0.contains("Order cannot be null"));
  }

  /*
   * @Test(timeout = 4000) public void test020() throws Throwable {
   * Schema.LockableArrayList<String> schema_LockableArrayList0 = new
   * Schema.LockableArrayList<String>(); Schema schema0 =
   * Schema.createEnum((String) null, "o", "&lE{b!95*Sx[", (List<String>)
   * schema_LockableArrayList0); int int0 = schema0.computeHash();
   * assertEquals("o", schema0.getDoc()); assertEquals(1008264047, int0); }
   */

  @Test(timeout = 4000)
  public void test021() throws Throwable {
    Schema[] schemaArray0 = new Schema[7];
    Schema schema0 = Schema.createArray(schemaArray0[0]);
    // Undeclared exception!
    try {
      schema0.writeReplace();
      fail("Expecting exception: NullPointerException");

    } catch (NullPointerException e) {
      //
      // no message in exception (getMessage() returned null)
      //
      verifyException("org.apache.avro.Schema$ArraySchema", e);
    }
  }

  @Test(timeout = 4000)
  public void test022() throws Throwable {
    Schema.LockableArrayList<String> schema_LockableArrayList0 = new Schema.LockableArrayList<String>();
    Schema schema0 = Protocol.SYSTEM_ERRORS;
    TreeSet<String> treeSet0 = new TreeSet<String>(schema_LockableArrayList0);
    // Undeclared exception!
    try {
      schema0.toJson(treeSet0, (String) null, (JsonGenerator) null);
      fail("Expecting exception: NullPointerException");

    } catch (NullPointerException e) {
      //
      // no message in exception (getMessage() returned null)
      //
      verifyException("org.apache.avro.Schema$UnionSchema", e);
    }
  }

  @Test(timeout = 4000)
  public void test023() throws Throwable {
    // Undeclared exception!
    try {
      Schema.parseJsonToObject((String) null);
      fail("Expecting exception: NullPointerException");

    } catch (NullPointerException e) {
      //
      // no message in exception (getMessage() returned null)
      //
      verifyException("com.fasterxml.jackson.core.JsonFactory", e);
    }
  }

  @Test(timeout = 4000)
  public void test024() throws Throwable {
    // Undeclared exception!
    try {
      Schema.parseJson("Cp&NPCY=b&MoN58^U");
      fail("Expecting exception: RuntimeException");

    } catch (RuntimeException e) {
      //
      // com.fasterxml.jackson.core.JsonParseException: Unrecognized token 'Cp': was
      // expecting (JSON String, Number, Array, Object or token 'null', 'true' or
      // 'false')
      // at [Source: (String)\"Cp&NPCY=b&MoN58^U\"; line: 1, column: 3]
      //
      verifyException("org.apache.avro.Schema", e);
    }
  }

  @Test(timeout = 4000)
  public void test025() throws Throwable {
    // Undeclared exception!
    try {
      Schema.parse((String) null, true);
      fail("Expecting exception: NullPointerException");

    } catch (NullPointerException e) {
      //
      // no message in exception (getMessage() returned null)
      //
      verifyException("com.fasterxml.jackson.core.JsonFactory", e);
    }
  }

  @Test(timeout = 4000)
  public void test026() throws Throwable {
    // Undeclared exception!
    try {
      Schema.parse((String) null);
      fail("Expecting exception: NullPointerException");

    } catch (NullPointerException e) {
      //
      // no message in exception (getMessage() returned null)
      //
      verifyException("com.fasterxml.jackson.core.JsonFactory", e);
    }
  }

  /*
   * @Test(timeout = 4000) public void test027() throws Throwable {
   * PushbackInputStream pushbackInputStream0 = new
   * PushbackInputStream((InputStream) null, 2147483645); try {
   * Schema.parse((InputStream) pushbackInputStream0);
   * fail("Expecting exception: IOException");
   * 
   * } catch(IOException e) { // // Stream closed //
   * verifyException("java.io.PushbackInputStream", e); } }
   */

  @Test(timeout = 4000)
  public void test028() throws Throwable {
    // Undeclared exception!
    try {
      Schema.parse((File) null);
      fail("Expecting exception: NullPointerException");

    } catch (NullPointerException e) {
      //
      // no message in exception (getMessage() returned null)
      //
      verifyException("org.evosuite.runtime.mock.java.io.MockFileInputStream", e);
    }
  }

  @Test(timeout = 4000)
  public void test029() throws Throwable {
    MockFile mockFile0 = new MockFile("8Fxk", "'R02Z24ywP6");
    try {
      Schema.parse((File) mockFile0);
      fail("Expecting exception: FileNotFoundException");

    } catch (FileNotFoundException e) {
      //
      // no message in exception (getMessage() returned null)
      //
      verifyException("org.evosuite.runtime.mock.java.io.MockFileInputStream", e);
    }
  }

  /*
   * @Test(timeout = 4000) public void test030() throws Throwable {
   * JsonNodeFactory jsonNodeFactory0 = new JsonNodeFactory(false); ObjectNode
   * objectNode0 = jsonNodeFactory0.objectNode(); ObjectNode objectNode1 =
   * objectNode0.put((String) null, false); ParseContext parseContext0 = new
   * ParseContext(); // Undeclared exception! try { Schema.parse((JsonNode)
   * objectNode1, parseContext0, (String) null);
   * fail("Expecting exception: RuntimeException");
   * 
   * } catch(RuntimeException e) { // //
   * com.fasterxml.jackson.databind.JsonMappingException: [no message for
   * java.lang.NullPointerException] //
   * verifyException("com.fasterxml.jackson.databind.node.InternalNodeMapper", e);
   * } }
   */

  @Test(timeout = 4000)
  public void test031() throws Throwable {
    Schema schema0 = Schema.createMap((Schema) null);
    // Undeclared exception!
    try {
      schema0.hasEnumSymbol("default");
      fail("Expecting exception: NullPointerException");

    } catch (NullPointerException e) {
      //
      // no message in exception (getMessage() returned null)
      //
      verifyException("org.apache.avro.Schema$MapSchema", e);
    }
  }

  @Test(timeout = 4000)
  public void test032() throws Throwable {
    Schema schema0 = Schema.createMap((Schema) null);
    // Undeclared exception!
    try {
      schema0.getTypes();
      fail("Expecting exception: NullPointerException");

    } catch (NullPointerException e) {
      //
      // no message in exception (getMessage() returned null)
      //
      verifyException("org.apache.avro.Schema$MapSchema", e);
    }
  }

  @Test(timeout = 4000)
  public void test033() throws Throwable {
    Schema schema0 = Protocol.SYSTEM_ERRORS;
    // Undeclared exception!
    try {
      schema0.getFixedSize();
      fail("Expecting exception: RuntimeException");

    } catch (RuntimeException e) {
      //
      // Not fixed: [\"string\"]
      //
      verifyException("org.apache.avro.Schema", e);
    }
  }

  @Test(timeout = 4000)
  public void test034() throws Throwable {
    LinkedList<Schema> linkedList0 = new LinkedList<Schema>();
    Schema schema0 = Schema.createUnion((List<Schema>) linkedList0);
    // Undeclared exception!
    try {
      schema0.getEnumSymbols();
      fail("Expecting exception: RuntimeException");

    } catch (RuntimeException e) {
      //
      // Not an enum: []
      //
      verifyException("org.apache.avro.Schema", e);
    }
  }

  @Test(timeout = 4000)
  public void test035() throws Throwable {
    Stack<Schema.Field> stack0 = new Stack<Schema.Field>();
    Schema schema0 = Schema.createRecord((List<Schema.Field>) stack0);
    Schema[] schemaArray0 = new Schema[4];
    schemaArray0[0] = schema0;
    schemaArray0[1] = schema0;
    schemaArray0[2] = schema0;
    schemaArray0[3] = schema0;
    Schema.LockableArrayList<Schema> schema_LockableArrayList0 = new Schema.LockableArrayList<Schema>(schemaArray0);
    // Undeclared exception!
    try {
      Schema.createUnion((List<Schema>) schema_LockableArrayList0);
      fail("Expecting exception: RuntimeException");

    } catch (RuntimeException e) {
      //
      // Nameless in
      // union:[{\"type\":\"record\",\"fields\":[]},{\"type\":\"record\",\"fields\":[]},{\"type\":\"record\",\"fields\":[]},{\"type\":\"record\",\"fields\":[]}]
      //
      verifyException("org.apache.avro.Schema$UnionSchema", e);
    }
  }

  @Test(timeout = 4000)
  public void test036() throws Throwable {
    // Undeclared exception!
    try {
      Schema.createRecord((List<Schema.Field>) null);
      fail("Expecting exception: NullPointerException");

    } catch (NullPointerException e) {
      //
      // no message in exception (getMessage() returned null)
      //
      verifyException("org.apache.avro.Schema$RecordSchema", e);
    }
  }

  @Test(timeout = 4000)
  public void test037() throws Throwable {
    Vector<Schema.Field> vector0 = new Vector<Schema.Field>();
    // Undeclared exception!
    try {
      Schema.createRecord("-u", "-u", "-u", true, (List<Schema.Field>) vector0);
      fail("Expecting exception: RuntimeException");

    } catch (RuntimeException e) {
      //
      // Illegal initial character: -u
      //
      verifyException("org.apache.avro.Schema", e);
    }
  }

  @Test(timeout = 4000)
  public void test038() throws Throwable {
    // Undeclared exception!
    try {
      Schema.createFixed("WRITE_BIGDECIMAL_AS_PLAIN", "enum value '", "enum value '", (-38));
      fail("Expecting exception: RuntimeException");

    } catch (RuntimeException e) {
      //
      // Malformed data. Length is negative: -38
      //
      verifyException("org.apache.avro.SystemLimitException", e);
    }
  }

  @Test(timeout = 4000)
  public void test039() throws Throwable {
    // Undeclared exception!
    try {
      Schema.createFixed("Cannot use source of type ", "GDrB~Qe,Z}", "Cannot use source of type ", (-1541));
      fail("Expecting exception: RuntimeException");

    } catch (RuntimeException e) {
      //
      // Illegal character in: Cannot use source of type
      //
      verifyException("org.apache.avro.Schema", e);
    }
  }

  @Test(timeout = 4000)
  public void test040() throws Throwable {
    // Undeclared exception!
    try {
      Schema.createEnum("com.fasterxml.jackson.databind.util.internal.PrivateMaxEntriesMap.pr6fixes", "ed", "long",
          (List<String>) null, "com.fasterxml.jackson.databind.util.internal.PrivateMaxEntriesMap.pr6fixes");
      fail("Expecting exception: NullPointerException");

    } catch (NullPointerException e) {
      //
      // no message in exception (getMessage() returned null)
      //
    }
  }

  @Test(timeout = 4000)
  public void test041() throws Throwable {
    // Undeclared exception!
    try {
      Schema.createEnum("org.apache.avro.compiler.UnresolvedSchema_45", "org.apache.avro.compiler.UnresolvedSchema_5",
          "org.apache.avro.compiler.UnresolvedSchema_5", (List<String>) null);
      fail("Expecting exception: NullPointerException");

    } catch (NullPointerException e) {
      //
      // no message in exception (getMessage() returned null)
      //
    }
  }

  @Test(timeout = 4000)
  public void test042() throws Throwable {
    Schema.LockableArrayList<String> schema_LockableArrayList0 = new Schema.LockableArrayList<String>();
    Schema schema0 = Schema.createEnum((String) null, "o", "&lE{b!95*Sx[", (List<String>) schema_LockableArrayList0);
    // Undeclared exception!
    try {
      schema0.addProp("com.fasterxml.jackson.databind.ser.BeanSerializer", (Object) null);
      fail("Expecting exception: RuntimeException");

    } catch (RuntimeException e) {
      //
      // Can't set a property to null:
      // com.fasterxml.jackson.databind.ser.BeanSerializer
      //
      verifyException("org.apache.avro.JsonProperties", e);
    }
  }

  @Test(timeout = 4000)
  public void test043() throws Throwable {
    NameValidator nameValidator0 = Schema.getNameValidator();
    ParseContext parseContext0 = new ParseContext(nameValidator0);
    Schema schema0 = parseContext0.find("No type", "No type");
    // Undeclared exception!
    try {
      schema0.addAlias("cbC[");
      fail("Expecting exception: RuntimeException");

    } catch (RuntimeException e) {
      //
      // Illegal character in: cbC[
      //
      verifyException("org.apache.avro.Schema", e);
    }
  }

  @Test(timeout = 4000)
  public void test044() throws Throwable {
    NameValidator nameValidator0 = Schema.getNameValidator();
    ParseContext parseContext0 = new ParseContext(nameValidator0);
    // Undeclared exception!
    try {
      Schema.parse((JsonNode) null, parseContext0, "prefixes");
      fail("Expecting exception: RuntimeException");

    } catch (RuntimeException e) {
      //
      // Cannot parse <null> schema
      //
      verifyException("org.apache.avro.Schema", e);
    }
  }

  @Test(timeout = 4000)
  public void test045() throws Throwable {
    Schema.Name schema_Name0 = new Schema.Name("pr6fixes", "");
    assertEquals("pr6fixes", schema_Name0.toString());
  }

  @Test(timeout = 4000)
  public void test046() throws Throwable {
    Schema.Name schema_Name0 = new Schema.Name("}.,cf_R,<agLhwj.Wl", (String) null);
    assertEquals("}.,cf_R,<agLhwj.Wl", schema_Name0.toString());
  }

  @Test(timeout = 4000)
  public void test047() throws Throwable {
    Schema schema0 = Protocol.SYSTEM_ERRORS;
    LinkedHashSet<String> linkedHashSet0 = new LinkedHashSet<String>();
    String string0 = schema0.toString((Set<String>) linkedHashSet0, false);
    assertEquals("[\"string\"]", string0);
  }

  @Test(timeout = 4000)
  public void test048() throws Throwable {
    ParseContext parseContext0 = new ParseContext();
    Schema.Parser schema_Parser0 = new Schema.Parser(parseContext0);
    URI uRI0 = MockURI.aFileURI;
    MockFile mockFile0 = new MockFile(uRI0);
    try {
      schema_Parser0.parse((File) mockFile0);
      fail("Expecting exception: FileNotFoundException");

    } catch (FileNotFoundException e) {
      //
      // no message in exception (getMessage() returned null)
      //
      verifyException("org.evosuite.runtime.mock.java.io.MockFileInputStream", e);
    }
  }

  @Test(timeout = 4000)
  public void test049() throws Throwable {
    Schema schema0 = Schema.createRecord((String) null, (String) null, "Order cannot be null", true);
    String string0 = schema0.toString(false);
    assertEquals("{\"type\":\"error\"}", string0);
  }

  @Test(timeout = 4000)
  public void test050() throws Throwable {
    NameValidator nameValidator0 = Schema.getNameValidator();
    ParseContext parseContext0 = new ParseContext(nameValidator0);
    Schema.Parser schema_Parser0 = new Schema.Parser(parseContext0);
    PushbackInputStream pushbackInputStream0 = new PushbackInputStream((InputStream) null, 320);
    try {
      schema_Parser0.parse((InputStream) pushbackInputStream0);
      fail("Expecting exception: IOException");

    } catch (IOException e) {
      //
      // Stream closed
      //
      verifyException("java.io.PushbackInputStream", e);
    }
  }

  @Test(timeout = 4000)
  public void test051() throws Throwable {
    Schema.LockableArrayList<String> schema_LockableArrayList0 = new Schema.LockableArrayList<String>();
    Schema.LockableArrayList<String> schema_LockableArrayList1 = new Schema.LockableArrayList<String>(
        schema_LockableArrayList0);
    assertEquals(0, schema_LockableArrayList1.size());
  }

  @Test(timeout = 4000)
  public void test052() throws Throwable {
    Schema.LockableArrayList<Object> schema_LockableArrayList0 = new Schema.LockableArrayList<Object>();
    List<Object> list0 = schema_LockableArrayList0.lock();
    assertTrue(list0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test053() throws Throwable {
    Schema.LockableArrayList<String> schema_LockableArrayList0 = new Schema.LockableArrayList<String>();
    Schema schema0 = Schema.createEnum((String) null, "o", "&lE{b!95*Sx[", (List<String>) schema_LockableArrayList0);
    String string0 = schema0.toString();
    assertEquals("{\"type\":\"enum\",\"doc\":\"o\",\"symbols\":[]}", string0);
  }

  @Test(timeout = 4000)
  public void test054() throws Throwable {
    Schema.LockableArrayList<String> schema_LockableArrayList0 = new Schema.LockableArrayList<String>();
    Schema schema0 = Schema.createEnum("pr6fixes", "Nested union: ",
        "com.fasterxml.jackson.databind.util.internal.PrivateMaxEntriesMap", (List<String>) schema_LockableArrayList0);
    NameValidator nameValidator0 = Schema.getNameValidator();
    ParseContext parseContext0 = new ParseContext(nameValidator0);
    Schema schema1 = parseContext0.find("Nested union: ", "tl>");
    Schema schema2 = Schema.applyAliases(schema0, schema1);
    assertFalse(schema2.equals((Object) schema1));
    assertEquals("unresolved schema", schema1.getDoc());
    assertEquals("Nested union: ", schema2.getDoc());
  }

  @Test(timeout = 4000)
  public void test055() throws Throwable {
    ObjectMapper objectMapper0 = new ObjectMapper();
    JsonNode jsonNode0 = objectMapper0.valueToTree((Object) null);
    Set<String> set0 = Schema.parseAliases(jsonNode0);
    assertNull(set0);
  }

  @Test(timeout = 4000)
  public void test056() throws Throwable {
    ParseContext parseContext0 = new ParseContext();
    ObjectMapper objectMapper0 = Schema.MAPPER;
    ArrayNode arrayNode0 = objectMapper0.createArrayNode();
    Schema schema0 = Schema.parse((JsonNode) arrayNode0, parseContext0,
        "no int/Int-argument constructor/factory method to deserialize from Number value (%s)");
    assertTrue(schema0.isUnion());
  }

  @Test(timeout = 4000)
  public void test057() throws Throwable {
    BooleanNode booleanNode0 = BooleanNode.getTrue();
    ParseContext parseContext0 = new ParseContext();
    // Undeclared exception!
    try {
      Schema.parse((JsonNode) booleanNode0, parseContext0,
          "no int/Int-argument constructor/factory method to deserialize from Number value (%s)");
      fail("Expecting exception: RuntimeException");

    } catch (RuntimeException e) {
      //
      // Schema not yet supported: true
      //
      verifyException("org.apache.avro.Schema", e);
    }
  }

  @Test(timeout = 4000)
  public void test058() throws Throwable {
    Stack<String> stack0 = new Stack<String>();
    Schema schema0 = Schema.createFixed("org.apache.avro.compiler.UnresolvedSchema_5", "ftIW?Xm0plu:{dC", "gBmS", 122);
    Schema.Field.Order schema_Field_Order0 = Schema.Field.Order.IGNORE;
    Schema.Field schema_Field0 = null;
    try {
      schema_Field0 = new Schema.Field("_", schema0, "gBmS", stack0, schema_Field_Order0);
      fail("Expecting exception: RuntimeException");

    } catch (RuntimeException e) {
      //
      // Invalid default for field _: [] not a
      // {\"type\":\"fixed\",\"name\":\"UnresolvedSchema_5\",\"namespace\":\"org.apache.avro.compiler\",\"doc\":\"ftIW?Xm0plu:{dC\",\"size\":122}
      //
      verifyException("org.apache.avro.Schema", e);
    }
  }

  @Test(timeout = 4000)
  public void test059() throws Throwable {
    Schema schema0 = Schema.createMap((Schema) null);
    JsonNodeFactory jsonNodeFactory0 = JsonNodeFactory.instance;
    ObjectNode objectNode0 = new ObjectNode(jsonNodeFactory0);
    NumericNode numericNode0 = objectNode0.numberNode(0.0F);
    boolean boolean0 = schema0.isValidDefault(numericNode0);
    assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test060() throws Throwable {
    FloatNode floatNode0 = new FloatNode((-2059.597F));
    Schema schema0 = Schema.createRecord("pr6fixes", "com.fasterxml.jackson.coe.io.NumberOutput", "XoW/^e/$\"oDPi<@2o",
        false);
    Schema.Field.Order schema_Field_Order0 = Schema.Field.Order.DESCENDING;
    Schema.Field schema_Field0 = null;
    try {
      schema_Field0 = new Schema.Field("PADDING_REQUIRED", schema0, "", floatNode0, true, schema_Field_Order0);
      fail("Expecting exception: RuntimeException");

    } catch (RuntimeException e) {
      //
      // Invalid default for field PADDING_REQUIRED: -2059.597 not a
      // {\"type\":\"record\",\"name\":\"pr6fixes\",\"namespace\":\"XoW/^e/$\\\"oDPi<@2o\",\"doc\":\"com.fasterxml.jackson.coe.io.NumberOutput\"}
      //
      verifyException("org.apache.avro.Schema", e);
    }
  }

  @Test(timeout = 4000)
  public void test061() throws Throwable {
    FloatNode floatNode0 = new FloatNode((-2059.597F));
    List<String> list0 = floatNode0.findValuesAsText("Nested union: ");
    Schema schema0 = Schema.createEnum("pr6fixes", "pr6fixes", (String) null, list0);
    Schema.Field.Order schema_Field_Order0 = Schema.Field.Order.DESCENDING;
    Schema.Field schema_Field0 = null;
    try {
      schema_Field0 = new Schema.Field("PADDING_REQUIRED", schema0, "", floatNode0, true, schema_Field_Order0);
      fail("Expecting exception: RuntimeException");

    } catch (RuntimeException e) {
      //
      // Invalid default for field PADDING_REQUIRED: -2059.597 not a
      // {\"type\":\"enum\",\"name\":\"pr6fixes\",\"doc\":\"pr6fixes\",\"symbols\":[]}
      //
      verifyException("org.apache.avro.Schema", e);
    }
  }

  @Test(timeout = 4000)
  public void test062() throws Throwable {
    Stack<Schema.Field> stack0 = new Stack<Schema.Field>();
    Schema schema0 = Schema.createRecord((List<Schema.Field>) stack0);
    Schema.Names schema_Names0 = new Schema.Names();
    boolean boolean0 = schema_Names0.contains(schema0);
    assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test063() throws Throwable {
    // Undeclared exception!
    try {
      Schema.parse("org.apache.avro.compiler", false);
      fail("Expecting exception: RuntimeException");

    } catch (RuntimeException e) {
      //
      // com.fasterxml.jackson.core.JsonParseException: Unrecognized token 'org': was
      // expecting (JSON String, Number, Array, Object or token 'null', 'true' or
      // 'false')
      // at [Source: (String)\"org.apache.avro.compiler\"; line: 1, column: 4]
      //
      verifyException("org.apache.avro.Schema$Parser", e);
    }
  }

  @Test(timeout = 4000)
  public void test064() throws Throwable {
    Schema.Parser schema_Parser0 = new Schema.Parser();
    String[] stringArray0 = new String[7];
    // Undeclared exception!
    try {
      schema_Parser0.parse("org.apache.avro.compiler.UnresolvedSchema_1", stringArray0);
      fail("Expecting exception: RuntimeException");

    } catch (RuntimeException e) {
      //
      // com.fasterxml.jackson.core.JsonParseException: Unrecognized token 'org': was
      // expecting (JSON String, Number, Array, Object or token 'null', 'true' or
      // 'false')
      // at [Source:
      // (String)\"org.apache.avro.compiler.UnresolvedSchema_1nullnullnullnullnullnullnull\";
      // line: 1, column: 4]
      //
      verifyException("org.apache.avro.Schema$Parser", e);
    }
  }

  @Test(timeout = 4000)
  public void test065() throws Throwable {
    Schema.LockableArrayList<String> schema_LockableArrayList0 = new Schema.LockableArrayList<String>();
    Schema schema0 = Schema.createEnum((String) null, "o", "&lE{b!95*Sx[", (List<String>) schema_LockableArrayList0);
    Schema[] schemaArray0 = new Schema[0];
    Schema.LockableArrayList<Schema> schema_LockableArrayList1 = new Schema.LockableArrayList<Schema>(schemaArray0);
    schema_LockableArrayList1.add(schema0);
    LinkedHashSet<Schema> linkedHashSet0 = new LinkedHashSet<Schema>(schema_LockableArrayList1);
    Schema.Parser schema_Parser0 = new Schema.Parser();
    // Undeclared exception!
    try {
      schema_Parser0.addTypes((Iterable<Schema>) linkedHashSet0);
      fail("Expecting exception: NullPointerException");

    } catch (NullPointerException e) {
      //
      // no message in exception (getMessage() returned null)
      //
      verifyException("org.apache.avro.ParseContext", e);
    }
  }

  @Test(timeout = 4000)
  public void test066() throws Throwable {
    PriorityQueue<Schema> priorityQueue0 = new PriorityQueue<Schema>();
    Schema.Parser schema_Parser0 = new Schema.Parser();
    Schema.Parser schema_Parser1 = schema_Parser0.addTypes((Iterable<Schema>) priorityQueue0);
    assertTrue(schema_Parser1.getValidateDefaults());
  }

  @Test(timeout = 4000)
  public void test067() throws Throwable {
    Schema.Parser schema_Parser0 = new Schema.Parser((NameValidator) null);
    assertTrue(schema_Parser0.getValidateDefaults());
  }

  @Test(timeout = 4000)
  public void test068() throws Throwable {
    Schema schema0 = Schema.createFixed("o.o", (String) null, "NgbvBv_9`:;Ukt1x*", 717);
    // Undeclared exception!
    try {
      schema0.getElementType();
      fail("Expecting exception: RuntimeException");

    } catch (RuntimeException e) {
      //
      // Not an array:
      // {\"type\":\"fixed\",\"name\":\"o\",\"namespace\":\"o\",\"size\":717}
      //
      verifyException("org.apache.avro.Schema", e);
    }
  }

  @Test(timeout = 4000)
  public void test069() throws Throwable {
    Schema schema0 = Schema.createFixed("boolean", "9V;iA))LdGbE&lv", "_", 30);
    Schema schema1 = Schema.applyAliases(schema0, schema0);
    assertEquals("9V;iA))LdGbE&lv", schema1.getDoc());
  }

  @Test(timeout = 4000)
  public void test070() throws Throwable {
    Schema schema0 = Protocol.SYSTEM_ERRORS;
    Schema schema1 = Schema.applyAliases(schema0, schema0);
    assertEquals(Schema.Type.UNION, schema1.getType());
  }

  @Test(timeout = 4000)
  public void test071() throws Throwable {
    Schema schema0 = Schema.createMap((Schema) null);
    Schema[] schemaArray0 = new Schema[8];
    schemaArray0[0] = schema0;
    schemaArray0[1] = schema0;
    // Undeclared exception!
    try {
      Schema.createUnion(schemaArray0);
      fail("Expecting exception: RuntimeException");

    } catch (RuntimeException e) {
      //
      // Duplicate in union:map
      //
      verifyException("org.apache.avro.Schema$UnionSchema", e);
    }
  }

  @Test(timeout = 4000)
  public void test072() throws Throwable {
    Stack<Schema.Field> stack0 = new Stack<Schema.Field>();
    Schema schema0 = Schema.createRecord((List<Schema.Field>) stack0);
    Schema[] schemaArray0 = new Schema[4];
    schemaArray0[0] = schema0;
    Schema.LockableArrayList<Schema> schema_LockableArrayList0 = new Schema.LockableArrayList<Schema>(schemaArray0);
    // Undeclared exception!
    try {
      Schema.createUnion((List<Schema>) schema_LockableArrayList0);
      fail("Expecting exception: NullPointerException");

    } catch (NullPointerException e) {
      //
      // no message in exception (getMessage() returned null)
      //
      verifyException("org.apache.avro.Schema$UnionSchema", e);
    }
  }

  @Test(timeout = 4000)
  public void test073() throws Throwable {
    LinkedList<Schema> linkedList0 = new LinkedList<Schema>();
    Schema schema0 = Schema.createUnion((List<Schema>) linkedList0);
    Schema[] schemaArray0 = new Schema[1];
    schemaArray0[0] = schema0;
    // Undeclared exception!
    try {
      Schema.createUnion(schemaArray0);
      fail("Expecting exception: RuntimeException");

    } catch (RuntimeException e) {
      //
      // Nested union: [[]]
      //
      verifyException("org.apache.avro.Schema$UnionSchema", e);
    }
  }

  @Test(timeout = 4000)
  public void test074() throws Throwable {
    Schema schema0 = Schema.createMap((Schema) null);
    Schema schema1 = Schema.applyAliases(schema0, schema0);
    assertSame(schema0, schema1);
  }

  @Test(timeout = 4000)
  public void test075() throws Throwable {
    Schema.LockableArrayList<String> schema_LockableArrayList0 = new Schema.LockableArrayList<String>();
    Schema schema0 = Schema.createEnum((String) null, "o", "o", (List<String>) schema_LockableArrayList0);
    Schema schema1 = Schema.createArray(schema0);
    // Undeclared exception!
    try {
      Schema.applyAliases(schema1, (Schema) null);
      fail("Expecting exception: NullPointerException");

    } catch (NullPointerException e) {
      //
      // no message in exception (getMessage() returned null)
      //
      verifyException("org.apache.avro.Schema", e);
    }
  }

  @Test(timeout = 4000)
  public void test076() throws Throwable {
    Schema.LockableArrayList<String> schema_LockableArrayList0 = new Schema.LockableArrayList<String>();
    Schema schema0 = Schema.createEnum((String) null, "aliases", "aliases", (List<String>) schema_LockableArrayList0);
    // Undeclared exception!
    try {
      schema0.isError();
      fail("Expecting exception: RuntimeException");

    } catch (RuntimeException e) {
      //
      // Not a record: {\"type\":\"enum\",\"doc\":\"aliases\",\"symbols\":[]}
      //
      verifyException("org.apache.avro.Schema", e);
    }
  }

  @Test(timeout = 4000)
  public void test077() throws Throwable {
    Schema.LockableArrayList<String> schema_LockableArrayList0 = new Schema.LockableArrayList<String>();
    Schema schema0 = Schema.createEnum("pr6fixes", "pr6fixes", "pr6fixes", (List<String>) schema_LockableArrayList0);
    Schema schema1 = Schema.applyAliases(schema0, schema0);
    assertFalse(schema1.isUnion());
  }

  @Test(timeout = 4000)
  public void test078() throws Throwable {
    Schema.LockableArrayList<String> schema_LockableArrayList0 = new Schema.LockableArrayList<String>();
    Schema schema0 = Schema.createEnum("prefixes", "8x&z]bdn_", "8x&z]bdn_", (List<String>) schema_LockableArrayList0);
    Schema schema1 = Schema.createMap(schema0);
    Schema schema2 = Schema.applyAliases(schema0, schema1);
    assertFalse(schema2.equals((Object) schema1));
    assertEquals("8x&z]bdn_", schema2.getDoc());
    assertEquals(Schema.Type.ENUM, schema2.getType());
  }

  @Test(timeout = 4000)
  public void test079() throws Throwable {
    Schema.LockableArrayList<String> schema_LockableArrayList0 = new Schema.LockableArrayList<String>();
    Schema schema0 = Schema.createEnum((String) null, "o", "o", (List<String>) schema_LockableArrayList0);
    // Undeclared exception!
    try {
      schema0.getEnumOrdinal(")0^c|9DT#z~E1\\A.prefixes");
      fail("Expecting exception: RuntimeException");

    } catch (RuntimeException e) {
      //
      // enum value ')0^c|9DT#z~E1\\A.prefixes' is not in the enum symbol set: []
      //
      verifyException("org.apache.avro.Schema$EnumSchema", e);
    }
  }

  @Test(timeout = 4000)
  public void test080() throws Throwable {
    Schema.LockableArrayList<String> schema_LockableArrayList0 = new Schema.LockableArrayList<String>();
    Schema schema0 = Schema.createEnum("pr6fixes", "pr6fixes", "pr6fixes", (List<String>) schema_LockableArrayList0);
    boolean boolean0 = schema0.hasEnumSymbol("pr6fixes");
    assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test081() throws Throwable {
    Stack<String> stack0 = new Stack<String>();
    // Undeclared exception!
    try {
      Schema.createEnum((String) null, (String) null, "bytes", (List<String>) stack0, "bytes");
      fail("Expecting exception: RuntimeException");

    } catch (RuntimeException e) {
      //
      // The Enum Default: bytes is not in the enum symbol set: []
      //
      verifyException("org.apache.avro.Schema$EnumSchema", e);
    }
  }

  @Test(timeout = 4000)
  public void test082() throws Throwable {
    String[] stringArray0 = new String[2];
    stringArray0[0] = "logicalType";
    stringArray0[1] = "logicalType";
    Schema.LockableArrayList<String> schema_LockableArrayList0 = new Schema.LockableArrayList<String>(stringArray0);
    // Undeclared exception!
    try {
      Schema.createEnum("logicalType", "org.apache.avro.compiler.UnresolvedSchema_8", "logicalType",
          (List<String>) schema_LockableArrayList0);
      fail("Expecting exception: RuntimeException");

    } catch (RuntimeException e) {
      //
      // Duplicate enum symbol: logicalType
      //
      verifyException("org.apache.avro.Schema$EnumSchema", e);
    }
  }

  @Test(timeout = 4000)
  public void test083() throws Throwable {
    Schema.LockableArrayList<String> schema_LockableArrayList0 = new Schema.LockableArrayList<String>();
    schema_LockableArrayList0.add("GK");
    Schema schema0 = Schema.createEnum("org.apache.avro.compiler.UnresolvedSchema_5", (String) null, (String) null,
        (List<String>) schema_LockableArrayList0);
    assertFalse(schema0.isUnion());
  }

  @Test(timeout = 4000)
  public void test084() throws Throwable {
    ParseContext parseContext0 = new ParseContext();
    Schema schema0 = parseContext0.find(", copyCount=", ", copyCount=");
    schema0.hashCode();
    assertEquals("unresolved schema", schema0.getDoc());
  }

  @Test(timeout = 4000)
  public void test085() throws Throwable {
    Schema schema0 = Schema.createRecord((String) null, (String) null, (String) null, false);
    Schema schema1 = Schema.applyAliases(schema0, schema0);
    assertNull(schema1.getDoc());
  }

  @Test(timeout = 4000)
  public void test086() throws Throwable {
    Schema schema0 = Schema.createRecord((String) null, (String) null, "%^DD!.L +u+]", true);
    Schema.Name schema_Name0 = new Schema.Name((String) null, "%^DD!.L +u+]");
    Schema.Names schema_Names0 = new Schema.Names("org.apache.avro.compiler.UnresolvedSchema_33");
    schema_Names0.put(schema_Name0, schema0);
    // Undeclared exception!
    try {
      schema_Names0.put(schema_Name0, (Schema) null);
      fail("Expecting exception: RuntimeException");

    } catch (RuntimeException e) {
      //
      // Can't redefine: null
      //
      verifyException("org.apache.avro.Schema$Names", e);
    }
  }

  @Test(timeout = 4000)
  public void test087() throws Throwable {
    Schema schema0 = Schema.createRecord((String) null, (String) null, (String) null, false);
    boolean boolean0 = schema0.hasFields();
    assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test088() throws Throwable {
    Schema schema0 = Schema.createRecord((String) null, (String) null, "%^DD!.L +u+]", true);
    // Undeclared exception!
    try {
      schema0.getField((String) null);
      fail("Expecting exception: RuntimeException");

    } catch (RuntimeException e) {
      //
      // Schema fields not set yet
      //
      verifyException("org.apache.avro.Schema$RecordSchema", e);
    }
  }

  @Test(timeout = 4000)
  public void test089() throws Throwable {
    Stack<Schema.Field> stack0 = new Stack<Schema.Field>();
    Schema schema0 = Schema.createRecord((List<Schema.Field>) stack0);
    Schema.Field schema_Field0 = schema0.getField((String) null);
    assertNull(schema_Field0);
  }

  @Test(timeout = 4000)
  public void test090() throws Throwable {
    // Undeclared exception!
    try {
      Schema.createRecord("float", (String) null, (String) null, true);
      fail("Expecting exception: RuntimeException");

    } catch (RuntimeException e) {
      //
      // Schemas may not be named after primitives: float
      //
      verifyException("org.apache.avro.Schema$NamedSchema", e);
    }
  }

  @Test(timeout = 4000)
  public void test091() throws Throwable {
    Schema.Name schema_Name0 = new Schema.Name((String) null, " vs ");
    String string0 = schema_Name0.getQualified("union");
    assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test092() throws Throwable {
    Schema.Name schema_Name0 = new Schema.Name("default", "default");
    String string0 = schema_Name0.getQualified("default");
    assertEquals("default.default", schema_Name0.toString());
    assertEquals("default", string0);
  }

  @Test(timeout = 4000)
  public void test093() throws Throwable {
    Schema.Name schema_Name0 = new Schema.Name((String) null, (String) null);
    DeserializerFactoryConfig deserializerFactoryConfig0 = new DeserializerFactoryConfig();
    BeanDeserializerFactory beanDeserializerFactory0 = new BeanDeserializerFactory(deserializerFactoryConfig0);
    DefaultDeserializationContext.Impl defaultDeserializationContext_Impl0 = new DefaultDeserializationContext.Impl(
        beanDeserializerFactory0);
    BufferRecycler bufferRecycler0 = new BufferRecycler();
    ContentReference contentReference0 = ContentReference.rawReference(true, (Object) null);
    IOContext iOContext0 = new IOContext(bufferRecycler0, contentReference0, true);
    StringReader stringReader0 = new StringReader(":K; <0w");
    JsonFactory jsonFactory0 = Schema.FACTORY;
    DefaultSerializerProvider.Impl defaultSerializerProvider_Impl0 = new DefaultSerializerProvider.Impl();
    ObjectMapper objectMapper0 = new ObjectMapper(jsonFactory0, defaultSerializerProvider_Impl0,
        defaultDeserializationContext_Impl0);
    CharsToNameCanonicalizer charsToNameCanonicalizer0 = CharsToNameCanonicalizer.createRoot();
    char[] charArray0 = new char[9];
    ReaderBasedJsonParser readerBasedJsonParser0 = new ReaderBasedJsonParser(iOContext0, 0, stringReader0,
        objectMapper0, charsToNameCanonicalizer0, charArray0, 33, 83, true);
    TokenFilter tokenFilter0 = TokenFilter.INCLUDE_ALL;
    TokenFilter.Inclusion tokenFilter_Inclusion0 = TokenFilter.Inclusion.INCLUDE_ALL_AND_PATH;
    FilteringParserDelegate filteringParserDelegate0 = new FilteringParserDelegate(readerBasedJsonParser0, tokenFilter0,
        tokenFilter_Inclusion0, true);
    TokenBuffer tokenBuffer0 = defaultDeserializationContext_Impl0
        .bufferForInputBuffering((JsonParser) filteringParserDelegate0);
    schema_Name0.writeName("6pu]p5L}Dr3Z", tokenBuffer0);
    assertFalse(tokenBuffer0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test094() throws Throwable {
    Schema.Name schema_Name0 = new Schema.Name((String) null, (String) null);
    Schema.Names schema_Names0 = new Schema.Names();
    Stack<Schema.Field> stack0 = new Stack<Schema.Field>();
    Schema schema0 = Schema.createRecord((List<Schema.Field>) stack0);
    schema_Names0.add(schema0);
    Schema schema1 = schema_Names0.put(schema_Name0, schema0);
    assertEquals(Schema.Type.RECORD, schema1.getType());
  }

  @Test(timeout = 4000)
  public void test095() throws Throwable {
    NameValidator nameValidator0 = Schema.getNameValidator();
    Schema.Name schema_Name0 = new Schema.Name((String) null, (String) null);
    boolean boolean0 = schema_Name0.equals(nameValidator0);
    assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test096() throws Throwable {
    Schema.Names schema_Names0 = new Schema.Names();
    Schema schema0 = schema_Names0.get("UNION");
    assertNull(schema0);
  }

  @Test(timeout = 4000)
  public void test097() throws Throwable {
    Schema schema0 = Schema.createRecord("ARRAY", "org.apache.avro.Schema$SerializableSchema", "P#wm<WIEuW]", true);
    Schema.Field schema_Field0 = new Schema.Field("ARRAY", schema0);
    boolean boolean0 = schema_Field0.equals("P#wm<WIEuW]");
    assertEquals((-1), schema_Field0.pos());
    assertEquals("org.apache.avro.Schema$SerializableSchema", schema0.getDoc());
    assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test098() throws Throwable {
    Schema.LockableArrayList<String> schema_LockableArrayList0 = new Schema.LockableArrayList<String>();
    Schema schema0 = Schema.createEnum((String) null, "o", "o", (List<String>) schema_LockableArrayList0);
    Schema.Field.Order schema_Field_Order0 = Schema.Field.Order.IGNORE;
    Schema.Field schema_Field0 = new Schema.Field("o", schema0, "com.fasterxml.jackson.databind.cfg", "UNION",
        schema_Field_Order0);
    schema_Field0.aliases();
    assertEquals("com.fasterxml.jackson.databind.cfg", schema_Field0.doc());
    assertEquals((-1), schema_Field0.pos());
  }

  @Test(timeout = 4000)
  public void test099() throws Throwable {
    Schema schema0 = Schema.createRecord("ARRAY", "org.apache.avro.Schema$SerializableSchema", "P#wm<WIEuW]", true);
    Schema.Field schema_Field0 = new Schema.Field("ARRAY", schema0);
    Schema.Field schema_Field1 = new Schema.Field(schema_Field0, schema0);
    assertEquals((-1), schema_Field1.pos());
    assertEquals("org.apache.avro.Schema$SerializableSchema", schema0.getDoc());
  }

  @Test(timeout = 4000)
  public void test100() throws Throwable {
    Schema schema0 = Protocol.SYSTEM_ERRORS;
    boolean boolean0 = schema0.isNullable();
    assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test101() throws Throwable {
    Schema schema0 = Protocol.SYSTEM_ERRORS;
    Schema[] schemaArray0 = new Schema[0];
    Schema.LockableArrayList<Schema> schema_LockableArrayList0 = new Schema.LockableArrayList<Schema>(schemaArray0);
    schema_LockableArrayList0.add(schema0);
    LinkedHashSet<Schema> linkedHashSet0 = new LinkedHashSet<Schema>(schema_LockableArrayList0);
    assertTrue(linkedHashSet0.contains(schema0));
  }

  @Test(timeout = 4000)
  public void test102() throws Throwable {
    Schema schema0 = Protocol.SYSTEM_ERROR;
    Schema schema1 = Schema.applyAliases(schema0, schema0);
    assertSame(schema0, schema1);
  }

  @Test(timeout = 4000)
  public void test103() throws Throwable {
    Schema schema0 = Protocol.SYSTEM_ERROR;
    boolean boolean0 = schema0.equals((Object) null);
    assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test104() throws Throwable {
    Schema schema0 = Protocol.SYSTEM_ERROR;
    // Undeclared exception!
    try {
      schema0.addAlias("Invalid numeric value: ", "org.apache.avro.compiler.UnresolvedSchema_1");
      fail("Expecting exception: RuntimeException");

    } catch (RuntimeException e) {
      //
      // Not a named type: \"string\"
      //
      verifyException("org.apache.avro.Schema", e);
    }
  }

  @Test(timeout = 4000)
  public void test105() throws Throwable {
    LinkedList<Schema> linkedList0 = new LinkedList<Schema>();
    Schema schema0 = Schema.createUnion((List<Schema>) linkedList0);
    String string0 = schema0.toString((Collection<Schema>) linkedList0, true);
    assertEquals("[ ]", string0);
  }

  @Test(timeout = 4000)
  public void test106() throws Throwable {
    Schema schema0 = Protocol.SYSTEM_ERRORS;
    String string0 = schema0.toString((Collection<Schema>) null, true);
    assertEquals("[ \"string\" ]", string0);
  }

  @Test(timeout = 4000)
  public void test107() throws Throwable {
    Schema.Type schema_Type0 = Schema.Type.RECORD;
    // Undeclared exception!
    try {
      Schema.create(schema_Type0);
      fail("Expecting exception: RuntimeException");

    } catch (RuntimeException e) {
      //
      // Can't create a: RECORD
      //
      verifyException("org.apache.avro.Schema", e);
    }
  }

  @Test(timeout = 4000)
  public void test108() throws Throwable {
    Schema.Type schema_Type0 = Schema.Type.ARRAY;
    String string0 = schema_Type0.getName();
    assertEquals("array", string0);
  }

  @Test(timeout = 4000)
  public void test109() throws Throwable {
    Schema.Names schema_Names0 = new Schema.Names();
    Schema schema0 = schema_Names0.get("string");
    assertEquals(Schema.Type.STRING, schema0.getType());
  }

  @Test(timeout = 4000)
  public void test110() throws Throwable {
    Schema.Type schema_Type0 = Schema.Type.INT;
    Schema schema0 = Schema.create(schema_Type0);
    ObjectMapper objectMapper0 = Schema.MAPPER;
    ArrayNode arrayNode0 = objectMapper0.createArrayNode();
    boolean boolean0 = schema0.isValidDefault(arrayNode0);
    assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test111() throws Throwable {
    Schema.Type schema_Type0 = Schema.Type.BYTES;
    Schema schema0 = Schema.create(schema_Type0);
    assertFalse(schema0.isUnion());
  }

  @Test(timeout = 4000)
  public void test112() throws Throwable {
    Schema.Type schema_Type0 = Schema.Type.NULL;
    Schema schema0 = Schema.create(schema_Type0);
    assertNull(schema0.getDoc());
  }

  @Test(timeout = 4000)
  public void test113() throws Throwable {
    Schema.Type schema_Type0 = Schema.Type.DOUBLE;
    Schema schema0 = Schema.create(schema_Type0);
    assertNull(schema0.getDoc());
  }

  @Test(timeout = 4000)
  public void test114() throws Throwable {
    Schema schema0 = Protocol.SYSTEM_ERRORS;
    Schema schema1 = Schema.createArray(schema0);
    Schema schema2 = Schema.applyAliases(schema0, schema1);
    assertFalse(schema2.equals((Object) schema1));
    assertEquals(Schema.Type.UNION, schema2.getType());
    assertSame(schema2, schema0);
  }

  @Test(timeout = 4000)
  public void test115() throws Throwable {
    Schema.Type schema_Type0 = Schema.Type.LONG;
    Schema schema0 = Schema.create(schema_Type0);
    Schema schema1 = Schema.createArray(schema0);
    // Undeclared exception!
    try {
      schema1.getFields();
      fail("Expecting exception: RuntimeException");

    } catch (RuntimeException e) {
      //
      // Not a record: {\"type\":\"array\",\"items\":\"long\"}
      //
      verifyException("org.apache.avro.Schema", e);
    }
  }

  @Test(timeout = 4000)
  public void test116() throws Throwable {
    Schema schema0 = Schema.createFixed("C3!Zo,fbL4.prefixes", "ARRAY.BY", "ARRAY.BY", 442);
    int int0 = schema0.computeHash();
    // // Unstable assertion: assertEquals(314116780, int0);
    // // Unstable assertion: assertEquals("ARRAY.BY", schema0.getDoc());
  }

  @Test(timeout = 4000)
  public void test117() throws Throwable {
    ParseContext parseContext0 = new ParseContext();
    Schema schema0 = parseContext0.find("hoI#&t4M<d[", "Not a named type: ");
    schema0.addAlias("i");
    assertEquals("unresolved schema", schema0.getDoc());
  }

  @Test(timeout = 4000)
  public void test118() throws Throwable {
    ObjectMapper.DefaultTyping objectMapper_DefaultTyping0 = ObjectMapper.DefaultTyping.OBJECT_AND_NON_CONCRETE;
    Schema.SeenPair schema_SeenPair0 = new Schema.SeenPair(objectMapper_DefaultTyping0, "ftIW?Xm0plu:{dC");
    Schema schema0 = Protocol.SYSTEM_ERRORS;
    boolean boolean0 = schema_SeenPair0.equals(schema0);
    assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test119() throws Throwable {
    Schema schema0 = Protocol.SYSTEM_ERRORS;
    String string0 = schema0.getName();
    assertEquals("union[string]", string0);
  }

  @Test(timeout = 4000)
  public void test120() throws Throwable {
    Schema.Names schema_Names0 = new Schema.Names();
    String string0 = schema_Names0.space();
    assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test121() throws Throwable {
    Schema.Names schema_Names0 = new Schema.Names();
    schema_Names0.space("^8L3$");
    assertEquals("^8L3$", schema_Names0.space());
  }

  @Test(timeout = 4000)
  public void test122() throws Throwable {
    Schema.LockableArrayList<String> schema_LockableArrayList0 = new Schema.LockableArrayList<String>();
    Schema schema0 = Schema.createEnum("prefixes", "8x&z]bdn_", "8x&z]bdn_", (List<String>) schema_LockableArrayList0);
    schema0.getEnumSymbols();
    assertEquals("8x&z]bdn_", schema0.getDoc());
  }

  @Test(timeout = 4000)
  public void test123() throws Throwable {
    ParseContext parseContext0 = new ParseContext();
    Schema.Parser schema_Parser0 = new Schema.Parser(parseContext0);
    // Undeclared exception!
    try {
      schema_Parser0.parse("_");
      fail("Expecting exception: RuntimeException");

    } catch (RuntimeException e) {
      //
      // com.fasterxml.jackson.core.JsonParseException: Unrecognized token '_': was
      // expecting (JSON String, Number, Array, Object or token 'null', 'true' or
      // 'false')
      // at [Source: (String)\"_\"; line: 1, column: 2]
      //
      verifyException("org.apache.avro.Schema$Parser", e);
    }
  }

  @Test(timeout = 4000)
  public void test124() throws Throwable {
    Schema.Parser schema_Parser0 = new Schema.Parser();
    schema_Parser0.setValidateDefaults(true);
    assertTrue(schema_Parser0.getValidateDefaults());
  }

  @Test(timeout = 4000)
  public void test125() throws Throwable {
    Schema.Parser schema_Parser0 = new Schema.Parser();
    schema_Parser0.getTypes();
    assertTrue(schema_Parser0.getValidateDefaults());
  }

  @Test(timeout = 4000)
  public void test126() throws Throwable {
    Schema.Name schema_Name0 = new Schema.Name((String) null, (String) null);
    String string0 = schema_Name0.toString();
    assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test127() throws Throwable {
    ObjectMapper objectMapper0 = Schema.MAPPER;
    ArrayNode arrayNode0 = objectMapper0.createArrayNode();
    ObjectNode objectNode0 = arrayNode0.insertObject((-1442984363));
    Schema.Type schema_Type0 = Schema.Type.BOOLEAN;
    Schema schema0 = Schema.create(schema_Type0);
    boolean boolean0 = schema0.isValidDefault(objectNode0);
    assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test128() throws Throwable {
    Stack<String> stack0 = new Stack<String>();
    Schema schema0 = Schema.createEnum((String) null, (String) null, (String) null, (List<String>) stack0,
        (String) null);
    // Undeclared exception!
    try {
      schema0.addAlias("I<_", "yKTO8*tDOHpi6");
      fail("Expecting exception: RuntimeException");

    } catch (RuntimeException e) {
      //
      // Illegal character in: I<_
      //
      verifyException("org.apache.avro.Schema", e);
    }
  }

  @Test(timeout = 4000)
  public void test129() throws Throwable {
    // Undeclared exception!
    try {
      Schema.parse("<l4qv*>B(GM}1m{#");
      fail("Expecting exception: RuntimeException");

    } catch (RuntimeException e) {
      //
      // com.fasterxml.jackson.core.JsonParseException: Unexpected character ('<'
      // (code 60)): expected a valid value (JSON String, Number, Array, Object or
      // token 'null', 'true' or 'false')
      // at [Source: (String)\"<l4qv*>B(GM}1m{#\"; line: 1, column: 2]
      //
      verifyException("org.apache.avro.Schema$Parser", e);
    }
  }

  @Test(timeout = 4000)
  public void test130() throws Throwable {
    Schema schema0 = Protocol.SYSTEM_ERRORS;
    // Undeclared exception!
    try {
      schema0.hasEnumSymbol("[\"string\"]");
      fail("Expecting exception: RuntimeException");

    } catch (RuntimeException e) {
      //
      // Not an enum: [\"string\"]
      //
      verifyException("org.apache.avro.Schema", e);
    }
  }

  @Test(timeout = 4000)
  public void test131() throws Throwable {
    Stack<String> stack0 = new Stack<String>();
    Schema schema0 = Schema.createEnum("org.apache.avro.compiler.UnresolvedSchema_48", (String) null, (String) null,
        (List<String>) stack0);
    // Undeclared exception!
    try {
      schema0.setFields((List<Schema.Field>) null);
      fail("Expecting exception: RuntimeException");

    } catch (RuntimeException e) {
      //
      // Not a record:
      // {\"type\":\"enum\",\"name\":\"UnresolvedSchema_48\",\"namespace\":\"org.apache.avro.compiler\",\"symbols\":[]}
      //
      verifyException("org.apache.avro.Schema", e);
    }
  }

  @Test(timeout = 4000)
  public void test132() throws Throwable {
    File file0 = MockFile.createTempFile("yME5Zq?fFD.eD(OJ", "Field already used: ");
    // Undeclared exception!
    try {
      Schema.parse(file0);
      fail("Expecting exception: RuntimeException");

    } catch (RuntimeException e) {
      //
      // Cannot parse <null> schema
      //
      verifyException("org.apache.avro.Schema", e);
    }
  }

  @Test(timeout = 4000)
  public void test133() throws Throwable {
    boolean boolean0 = Schema.getValidateDefaults();
    assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test134() throws Throwable {
    Stack<Schema.Field> stack0 = new Stack<Schema.Field>();
    Schema schema0 = Schema.createRecord((List<Schema.Field>) stack0);
    ObjectMapper objectMapper0 = new ObjectMapper();
    try {
      objectMapper0.valueToTree((Object) schema0);
      fail("Expecting exception: IllegalArgumentException");

    } catch (IllegalArgumentException e) {
      //
      // Not fixed: {\"type\":\"record\",\"fields\":[]} (through reference chain:
      // org.apache.avro.Schema$RecordSchema[\"fixedSize\"])
      //
      verifyException("com.fasterxml.jackson.databind.ObjectMapper", e);
    }
  }

  @Test(timeout = 4000)
  public void test135() throws Throwable {
    Schema schema0 = Schema.createRecord((String) null, (String) null, (String) null, false);
    // Undeclared exception!
    try {
      schema0.getEnumDefault();
      fail("Expecting exception: RuntimeException");

    } catch (RuntimeException e) {
      //
      // Not an enum: {\"type\":\"record\"}
      //
      verifyException("org.apache.avro.Schema", e);
    }
  }

  @Test(timeout = 4000)
  public void test136() throws Throwable {
    Schema schema0 = Protocol.SYSTEM_ERROR;
    String string0 = schema0.getFullName();
    assertEquals("string", string0);
  }

  @Test(timeout = 4000)
  public void test137() throws Throwable {
    Schema schema0 = Protocol.SYSTEM_ERROR;
    // Undeclared exception!
    try {
      schema0.addAlias("or.apache.avro.compiler.UnresolvedSchema_17");
      fail("Expecting exception: RuntimeException");

    } catch (RuntimeException e) {
      //
      // Not a named type: \"string\"
      //
      verifyException("org.apache.avro.Schema", e);
    }
  }

  @Test(timeout = 4000)
  public void test138() throws Throwable {
    Schema.LockableArrayList<String> schema_LockableArrayList0 = new Schema.LockableArrayList<String>();
    Schema schema0 = Schema.createEnum((String) null, (String) null, (String) null,
        (List<String>) schema_LockableArrayList0);
    Schema schema1 = Schema.createMap(schema0);
    Schema schema2 = Schema.applyAliases(schema1, schema0);
    schema2.getDoc();
    assertFalse(schema2.equals((Object) schema0));
    assertEquals(Schema.Type.MAP, schema2.getType());
  }

  @Test(timeout = 4000)
  public void test139() throws Throwable {
    Schema schema0 = Schema.createRecord("ARRAY", "org.apache.avro.Schema$SerializableSchema", "P#wm<WIEuW]", true);
    schema0.isUnion();
    assertEquals("org.apache.avro.Schema$SerializableSchema", schema0.getDoc());
  }

  @Test(timeout = 4000)
  public void test140() throws Throwable {
    Schema.Type schema_Type0 = Schema.Type.FLOAT;
    Schema schema0 = Schema.create(schema_Type0);
    Schema.Names schema_Names0 = new Schema.Names("x8Mhz:m:");
    schema0.addProp("!a8xG7c!,xl+:)##?", (Object) schema_Names0);
    assertEquals(Schema.Type.FLOAT, schema0.getType());
  }

  @Test(timeout = 4000)
  public void test141() throws Throwable {
    Schema.Type schema_Type0 = Schema.Type.BOOLEAN;
    Schema schema0 = Schema.create(schema_Type0);
    // Undeclared exception!
    try {
      schema0.getNamespace();
      fail("Expecting exception: RuntimeException");

    } catch (RuntimeException e) {
      //
      // Not a named type: \"boolean\"
      //
      verifyException("org.apache.avro.Schema", e);
    }
  }

  @Test(timeout = 4000)
  public void test142() throws Throwable {
    Schema schema0 = Protocol.SYSTEM_ERRORS;
    // Undeclared exception!
    try {
      schema0.hasFields();
      fail("Expecting exception: RuntimeException");

    } catch (RuntimeException e) {
      //
      // Not a record: [\"string\"]
      //
      verifyException("org.apache.avro.Schema", e);
    }
  }

  @Test(timeout = 4000)
  public void test143() throws Throwable {
    // Undeclared exception!
    try {
      Schema.parse((InputStream) null);
      fail("Expecting exception: RuntimeException");

    } catch (RuntimeException e) {
      //
      // Cannot parse <null> schema
      //
      verifyException("org.apache.avro.Schema", e);
    }
  }

  @Test(timeout = 4000)
  public void test144() throws Throwable {
    // Undeclared exception!
    try {
      Schema.parseJsonToObject("No digit following minus sign");
      fail("Expecting exception: RuntimeException");

    } catch (RuntimeException e) {
      //
      // com.fasterxml.jackson.core.JsonParseException: Unrecognized token 'No': was
      // expecting (JSON String, Number, Array, Object or token 'null', 'true' or
      // 'false')
      // at [Source: (String)\"No digit following minus sign\"; line: 1, column: 3]
      //
      verifyException("org.apache.avro.Schema", e);
    }
  }

  @Test(timeout = 4000)
  public void test145() throws Throwable {
    Schema schema0 = Protocol.SYSTEM_ERROR;
    // Undeclared exception!
    try {
      schema0.getTypes();
      fail("Expecting exception: RuntimeException");

    } catch (RuntimeException e) {
      //
      // Not a union: \"string\"
      //
      verifyException("org.apache.avro.Schema", e);
    }
  }

  @Test(timeout = 4000)
  public void test146() throws Throwable {
    Schema schema0 = Schema.createMap((Schema) null);
    // Undeclared exception!
    try {
      schema0.getEnumSymbols();
      fail("Expecting exception: NullPointerException");

    } catch (NullPointerException e) {
      //
      // no message in exception (getMessage() returned null)
      //
      verifyException("org.apache.avro.Schema$MapSchema", e);
    }
  }

  @Test(timeout = 4000)
  public void test147() throws Throwable {
    ParseContext parseContext0 = new ParseContext();
    Schema schema0 = parseContext0.find("hoI#&t4M<d[", "Not a named type: ");
    schema0.getLogicalType();
    assertEquals("unresolved schema", schema0.getDoc());
  }

  @Test(timeout = 4000)
  public void test148() throws Throwable {
    Schema[] schemaArray0 = new Schema[0];
    Schema.LockableArrayList<Schema> schema_LockableArrayList0 = new Schema.LockableArrayList<Schema>(schemaArray0);
    Schema schema0 = Schema.createUnion((List<Schema>) schema_LockableArrayList0);
    Schema schema1 = Schema.createMap(schema0);
    // Undeclared exception!
    try {
      schema1.getIndexNamed((String) null);
      fail("Expecting exception: RuntimeException");

    } catch (RuntimeException e) {
      //
      // Not a union: {\"type\":\"map\",\"values\":[]}
      //
      verifyException("org.apache.avro.Schema", e);
    }
  }

  @Test(timeout = 4000)
  public void test149() throws Throwable {
    Schema.Type schema_Type0 = Schema.Type.BOOLEAN;
    Schema schema0 = Schema.create(schema_Type0);
    // Undeclared exception!
    try {
      schema0.getAliases();
      fail("Expecting exception: RuntimeException");

    } catch (RuntimeException e) {
      //
      // Not a named type: \"boolean\"
      //
      verifyException("org.apache.avro.Schema", e);
    }
  }

  @Test(timeout = 4000)
  public void test150() throws Throwable {
    Schema.setValidateDefaults(false);
  }

  @Test(timeout = 4000)
  public void test151() throws Throwable {
    ParseContext parseContext0 = new ParseContext();
    Schema schema0 = parseContext0.find(", copyCount=", ", copyCount=");
    LogicalType logicalType0 = new LogicalType("ALLOW_LEADING_DECIMAL_POINT_FOR_NUMBERS");
    schema0.setLogicalType(logicalType0);
    assertEquals("unresolved schema", schema0.getDoc());
  }

  @Test(timeout = 4000)
  public void test152() throws Throwable {
    Schema schema0 = Schema.createRecord((String) null, (String) null, (String) null, true);
    Object object0 = schema0.writeReplace();
    assertNotNull(object0);
  }

  @Test(timeout = 4000)
  public void test153() throws Throwable {
    Schema schema0 = Schema.createRecord((String) null, (String) null, "Order cannot be null", true);
    // Undeclared exception!
    try {
      schema0.getEnumOrdinal("com.fasterxml.jackson.databind.ser.DefaultSerializerProvider");
      fail("Expecting exception: RuntimeException");

    } catch (RuntimeException e) {
      //
      // Not an enum: {\"type\":\"error\"}
      //
      verifyException("org.apache.avro.Schema", e);
    }
  }

  @Test(timeout = 4000)
  public void test154() throws Throwable {
    Schema[] schemaArray0 = new Schema[1];
    // Undeclared exception!
    try {
      Schema.createUnion(schemaArray0);
      fail("Expecting exception: NullPointerException");

    } catch (NullPointerException e) {
      //
      // no message in exception (getMessage() returned null)
      //
      verifyException("org.apache.avro.Schema$UnionSchema", e);
    }
  }

  @Test(timeout = 4000)
  public void test155() throws Throwable {
    Stack<Schema.Field> stack0 = new Stack<Schema.Field>();
    Schema schema0 = Schema.createRecord((List<Schema.Field>) stack0);
    // Undeclared exception!
    try {
      schema0.getValueType();
      fail("Expecting exception: RuntimeException");

    } catch (RuntimeException e) {
      //
      // Not a map: {\"type\":\"record\",\"fields\":[]}
      //
      verifyException("org.apache.avro.Schema", e);
    }
  }

  @Test(timeout = 4000)
  public void test156() throws Throwable {
    Schema.LockableArrayList<String> schema_LockableArrayList0 = new Schema.LockableArrayList<String>();
    Schema schema0 = Schema.createEnum("prefixes", "prefixes", "prefixes", (List<String>) schema_LockableArrayList0);
    schema0.addAlias("prefixes", "prefixes");
    assertFalse(schema_LockableArrayList0.contains("prefixes"));
  }

  @Test(timeout = 4000)
  public void test157() throws Throwable {
    Schema schema0 = Schema.createRecord("ARRAY", "org.apache.avro.Schema$SerializableSchema", "P#wm<WIEuW]", true);
    Schema.Field schema_Field0 = new Schema.Field("ARRAY", schema0);
    schema_Field0.defaultVal();
    assertEquals("org.apache.avro.Schema$SerializableSchema", schema0.getDoc());
    assertEquals((-1), schema_Field0.pos());
  }

  @Test(timeout = 4000)
  public void test158() throws Throwable {
    Schema schema0 = Protocol.SYSTEM_ERRORS;
    Schema.Field.Order schema_Field_Order0 = Schema.Field.Order.IGNORE;
    Schema.Field schema_Field0 = new Schema.Field("_", schema0, (String) null, (Object) null, schema_Field_Order0);
    schema_Field0.schema();
    assertEquals((-1), schema_Field0.pos());
  }

  @Test(timeout = 4000)
  public void test159() throws Throwable {
    Schema schema0 = Protocol.SYSTEM_ERRORS;
    Schema.Field schema_Field0 = new Schema.Field("prefixes", schema0, "prefixes");
    schema_Field0.order();
    assertEquals((-1), schema_Field0.pos());
  }

  @Test(timeout = 4000)
  public void test160() throws Throwable {
    Schema.LockableArrayList<JsonNode.OverwriteMode> schema_LockableArrayList0 = new Schema.LockableArrayList<JsonNode.OverwriteMode>();
    LinkedList<JsonNode.OverwriteMode> linkedList0 = new LinkedList<JsonNode.OverwriteMode>();
    // Undeclared exception!
    try {
      schema_LockableArrayList0.addAll((-347), (Collection<? extends JsonNode.OverwriteMode>) linkedList0);
      fail("Expecting exception: IndexOutOfBoundsException");

    } catch (IndexOutOfBoundsException e) {
      //
      // Index: -347, Size: 0
      //
      verifyException("java.util.ArrayList", e);
    }
  }

  @Test(timeout = 4000)
  public void test161() throws Throwable {
    Schema.LockableArrayList<String> schema_LockableArrayList0 = new Schema.LockableArrayList<String>();
    LinkedHashSet<String> linkedHashSet0 = new LinkedHashSet<String>();
    boolean boolean0 = schema_LockableArrayList0.addAll((Collection<? extends String>) linkedHashSet0);
    assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test162() throws Throwable {
    Schema.LockableArrayList<String> schema_LockableArrayList0 = new Schema.LockableArrayList<String>();
    Schema.Names schema_Names0 = new Schema.Names("&l{!95*Sx[");
    boolean boolean0 = schema_LockableArrayList0.remove((Object) schema_Names0);
    assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test163() throws Throwable {
    Stack<Schema> stack0 = new Stack<Schema>();
    Schema schema0 = Schema.createUnion((List<Schema>) stack0);
    // Undeclared exception!
    try {
      schema0.addProp("ARRAY.ARRAY", "ARRAY");
      fail("Expecting exception: RuntimeException");

    } catch (RuntimeException e) {
      //
      // Can't set properties on a union: []
      //
      verifyException("org.apache.avro.Schema$UnionSchema", e);
    }
  }

  /*
   * @Test(timeout = 4000) public void test164() throws Throwable {
   * Schema.LockableArrayList<HashMap<Object, FileVisitResult>>
   * schema_LockableArrayList0 = new Schema.LockableArrayList<HashMap<Object,
   * FileVisitResult>>(1861); // Undeclared exception! try {
   * schema_LockableArrayList0.remove(2);
   * fail("Expecting exception: IndexOutOfBoundsException");
   * 
   * } catch(IndexOutOfBoundsException e) { // // Index: 2, Size: 0 //
   * verifyException("java.util.ArrayList", e); } }
   */

  @Test(timeout = 4000)
  public void test165() throws Throwable {
    Schema.LockableArrayList<FileVisitResult> schema_LockableArrayList0 = new Schema.LockableArrayList<FileVisitResult>();
    Vector<String> vector0 = new Vector<String>();
    boolean boolean0 = schema_LockableArrayList0.removeAll(vector0);
    assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test166() throws Throwable {
    Schema.LockableArrayList<String> schema_LockableArrayList0 = new Schema.LockableArrayList<String>();
    Schema.LockableArrayList<Schema.Field> schema_LockableArrayList1 = new Schema.LockableArrayList<Schema.Field>();
    boolean boolean0 = schema_LockableArrayList1.retainAll(schema_LockableArrayList0);
    assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test167() throws Throwable {
    Schema.LockableArrayList<String> schema_LockableArrayList0 = new Schema.LockableArrayList<String>();
    schema_LockableArrayList0.clear();
    assertTrue(schema_LockableArrayList0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test168() throws Throwable {
    Schema schema0 = Schema.createMap((Schema) null);
    // Undeclared exception!
    try {
      schema0.getField("4%^wU-Yg-9b");
      fail("Expecting exception: NullPointerException");

    } catch (NullPointerException e) {
      //
      // no message in exception (getMessage() returned null)
      //
      verifyException("org.apache.avro.Schema$MapSchema", e);
    }
  }
}
