/*
 * This file was automatically generated by EvoSuite
 * Tue Aug 18 08:19:18 GMT 2026
 */

package customTests.evosuite;

import org.junit.Test;
import java.util.List;
import java.util.Vector;
import org.apache.avro.ParseContext;
import org.apache.avro.Protocol;
import org.apache.avro.Schema;

import static org.evosuite.runtime.EvoAssertions.verifyException;
import static org.junit.Assert.assertNull;
import static org.junit.Assert.fail;
import static org.junit.Assert.assertEquals;

public class ParseContextESTest {

  @Test(timeout = 4000)
  public void test01() throws Throwable {
    ParseContext parseContext0 = new ParseContext();
    // Undeclared exception!
    try {
      parseContext0.find("hLoXhZ`", "hLoXhZ`");
      // fail("Expecting exception: NullPointerException");
      // Unstable assertion
    } catch (NullPointerException e) {
      //
      // no message in exception (getMessage() returned null)
      //
      verifyException("org.apache.avro.Schema", e);
    }
  }

  @Test(timeout = 4000)
  public void test02() throws Throwable {
    ParseContext parseContext0 = new ParseContext();
    Schema schema0 = parseContext0.find("boolean", "boolean");
    assertEquals(Schema.Type.BOOLEAN, schema0.getType());
  }

  @Test(timeout = 4000)
  public void test03() throws Throwable {
    ParseContext parseContext0 = new ParseContext();
    Schema schema0 = Protocol.SYSTEM_ERROR;
    Schema schema1 = parseContext0.resolve(schema0);
    assertNull(schema1.getDoc());
  }

  @Test(timeout = 4000)
  public void test04() throws Throwable {
    ParseContext parseContext0 = new ParseContext();
    // Undeclared exception!
    try {
      parseContext0.find(" lcY#BS6MjS{MIn&$}C", " lcY#BS6MjS{MIn&$}C");
      // fail("Expecting exception: NullPointerException");
      // Unstable assertion
    } catch (NullPointerException e) {
      //
      // no message in exception (getMessage() returned null)
      //
      verifyException("org.apache.avro.Schema", e);
    }
  }

  @Test(timeout = 4000)
  public void test05() throws Throwable {
    ParseContext parseContext0 = new ParseContext();
    // Undeclared exception!
    try {
      parseContext0.put((Schema) null);
      fail("Expecting exception: NullPointerException");

    } catch (NullPointerException e) {
      //
      // no message in exception (getMessage() returned null)
      //
      verifyException("org.apache.avro.ParseContext", e);
    }
  }

  @Test(timeout = 4000)
  public void test06() throws Throwable {
    ParseContext parseContext0 = new ParseContext();
    // Undeclared exception!
    try {
      parseContext0.find((String) null, "You can only put a named schema into the context");
      fail("Expecting exception: NullPointerException");

    } catch (NullPointerException e) {
      //
      // no message in exception (getMessage() returned null)
      //
      verifyException("org.apache.avro.ParseContext", e);
    }
  }

  @Test(timeout = 4000)
  public void test07() throws Throwable {
    ParseContext parseContext0 = new ParseContext();
    // Undeclared exception!
    try {
      parseContext0.find("org.apache.avro.ParseContext$1", "org.apache.avro.ParseContext$1");
      // fail("Expecting exception: NullPointerException");
      // Unstable assertion
    } catch (NullPointerException e) {
      //
      // no message in exception (getMessage() returned null)
      //
      verifyException("org.apache.avro.Schema", e);
    }
  }

  @Test(timeout = 4000)
  public void test08() throws Throwable {
    ParseContext parseContext0 = new ParseContext();
    Schema schema0 = Schema.createRecord((String) null, (String) null, (String) null, false);
    // Undeclared exception!
    try {
      parseContext0.resolve(schema0);
      fail("Expecting exception: RuntimeException");

    } catch (RuntimeException e) {
      //
      // Schema fields not set yet
      //
      verifyException("org.apache.avro.Schema$RecordSchema", e);
    }
  }

  @Test(timeout = 4000)
  public void test09() throws Throwable {
    ParseContext parseContext0 = new ParseContext();
    // Undeclared exception!
    try {
      parseContext0.find("b[}N9Vndki/F(Trl", "b[}N9Vndki/F(Trl");
      // fail("Expecting exception: NullPointerException");
      // Unstable assertion
    } catch (NullPointerException e) {
      //
      // no message in exception (getMessage() returned null)
      //
      verifyException("org.apache.avro.Schema", e);
    }
  }

  @Test(timeout = 4000)
  public void test10() throws Throwable {
    ParseContext parseContext0 = new ParseContext();
    // Undeclared exception!
    try {
      parseContext0.find("hLoXhZ`", "n) fT)*(gP.[4;Rc)");
      // fail("Expecting exception: NullPointerException");
      // Unstable assertion
    } catch (NullPointerException e) {
      //
      // no message in exception (getMessage() returned null)
      //
      verifyException("org.apache.avro.Schema", e);
    }
  }

  @Test(timeout = 4000)
  public void test11() throws Throwable {
    ParseContext parseContext0 = new ParseContext();
    // Undeclared exception!
    try {
      parseContext0.find("NavespaVe part", "NavespaVe part");
      // fail("Expecting exception: NullPointerException");
      // Unstable assertion
    } catch (NullPointerException e) {
      //
      // no message in exception (getMessage() returned null)
      //
      verifyException("org.apache.avro.Schema", e);
    }
  }

  @Test(timeout = 4000)
  public void test12() throws Throwable {
    ParseContext parseContext0 = new ParseContext();
    Vector<Schema> vector0 = new Vector<Schema>();
    Schema schema0 = Schema.createUnion((List<Schema>) vector0);
    // Undeclared exception!
    try {
      parseContext0.put(schema0);
      fail("Expecting exception: RuntimeException");

    } catch (RuntimeException e) {
      //
      // You can only put a named schema into the context
      //
      verifyException("org.apache.avro.ParseContext", e);
    }
  }

  @Test(timeout = 4000)
  public void test13() throws Throwable {
    ParseContext parseContext0 = new ParseContext();
    // Undeclared exception!
    try {
      parseContext0.find(".", ".");
      // fail("Expecting exception: NullPointerException");
      // Unstable assertion
    } catch (NullPointerException e) {
      //
      // no message in exception (getMessage() returned null)
      //
      verifyException("org.apache.avro.Schema", e);
    }
  }

}
