name: Apache Avro CI

on:
  push:
    branches:
      - main
      - master
      - custom-tests

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: maven

      - name: Build with Maven
        run: mvn -B clean verify 
          -DskipTests
          -Drat.skip=true
          -DfailIfNoTests=false
          -Dinvoker.skip=true


      - name: Run custom tests
        run: mvn -pl lang/java/avro -am verify
          -Dtest=customTests.manual.ParseContextBBTest,customTests.controlFlow.ParseContextCFTest,customTests.mutation.ParseContextMTTest,customTests.randoop.generated.RandoopRunTest 
          -Dit.test=customTests.manual.ParseContextTestIT 
          -DfailIfNoTests=false 
          -Dinvoker.skip=true 
          -Drat.skip=true
          -Dmaven.build.cache.enabled=false
