name: Apache Avro CI

on:
  push:
    branches:
      - main
      - master
      - custom-tests

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: maven

      - name: Build with Maven
        run: mvn -B clean verify 
          -DskipTests
          -Drat.skip=true
          -Dinvoker.skip=true


      - name: Run custom tests
        run: mvn -B -Dtest=ParseContextUnitTest test
             #mvn -B -Dtest="customTests.**.*" test
